### PR TITLE
listen-support

### PR DESCRIPTION
**Pull request by heywood8**
---
name: Pull request
about: Add "Listen" block support

### CODE REVIEW

**Comment by heywood8** [comment]
#12 Linking the issue

**Comment by heywood8** [comment]
@robertdebock, can you take a look ?

**Comment by robertdebock** [comment]
Hey,

CI is failing, please have a look:

```
TASK [ansible-role-haproxy : assert | Test if item in haproxy_listens is set correctly] ***
failed: [haproxy-fedora-37py310-ansible8 -> localhost] (item=listen) => {"ansible_loop_var": "item", "assertion": "item.address is defined", "changed": false, "evaluated_to": false, "item": {"balance": "roundrobin", "httpcheck": true, "listen_port": 8081, "name": "listen", "options": ["maxconn 100000"], "port": 8080, "servers": ["haproxy-fedora-37py310-ansible8"]}, "msg": "Assertion failed"}
```

**Comment by heywood8** [comment]
> Hey,
> 
> CI is failing, please have a look:

My bad.
Added missing value for test and readme. On my fork checks are passing now

**Comment by robertdebock** [comment]
Thanks a lot! I've added argument_specs since, so expect a few commits before releasing a new version.

**Pull request merged**
